/**
 * Seed the FalModel catalog. Pricing data sourced from fal.ai/pricing and
 * https://gist.github.com/azer/6e8ffa228cb5d6f5807cd4d895b191a4.
 *
 *   pnpm db:seed:fal
 *
 * Re-running upserts; safe to repeat.
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type ModelSeed = {
  slug: string;
  category:
    | "video"
    | "image"
    | "audio"
    | "lipsync"
    | "upscale"
    | "3d"
    | "avatar"
    | "vision"
    | "tts"
    | "stt"
    | "training"
    | "text"
    | "effects";
  displayName: string;
  description?: string;
  unit:
    | "per_second"
    | "per_video"
    | "per_megapixel"
    | "per_image"
    | "per_1k_chars"
    | "per_minute"
    | "per_compute_second"
    | "per_request"
    | "per_generation"
    | "per_step"
    | "per_training_run"
    | "per_audio_second"
    | "per_video_second"
    | "per_5_second_video"
    | "per_4_second_video"
    | "per_10_seconds"
    | "per_template"
    | "per_voice"
    | "per_mask"
    | "per_unit";
  unitPriceUsd: number;
  capabilities?: Record<string, unknown>;
  features?: string[];
  badge?: "premium" | "fast" | "new" | "beta" | "hot";
  marketingBlurb?: string;
  sortIndex?: number;
};

// ---------------------------------------------------------------------------
// Video text-to-video and image-to-video
// ---------------------------------------------------------------------------
const VIDEO: ModelSeed[] = [
  // Google Veo
  {
    slug: "fal-ai/veo3.1",
    category: "video",
    displayName: "Veo 3.1",
    description: "Google's flagship text-to-video with synchronized native audio.",
    unit: "per_second",
    unitPriceUsd: 0.4,
    capabilities: { textToVideo: true, hasAudio: true, maxResolution: "1080p", durationOpts: [4, 6, 8] },
    features: ["text-to-video", "native-audio", "premium"],
    badge: "premium",
    marketingBlurb: "Cinematic generations with sound. The state-of-the-art baseline.",
    sortIndex: 1,
  },
  {
    slug: "fal-ai/veo3.1/fast",
    category: "video",
    displayName: "Veo 3.1 Fast",
    description: "Faster, cheaper Veo 3.1 variant.",
    unit: "per_second",
    unitPriceUsd: 0.2,
    capabilities: { textToVideo: true, hasAudio: false, maxResolution: "1080p", durationOpts: [4, 6, 8] },
    features: ["text-to-video", "fast"],
    badge: "fast",
    sortIndex: 2,
  },
  {
    slug: "fal-ai/veo3.1/image-to-video",
    category: "video",
    displayName: "Veo 3.1 (Image-to-Video)",
    description: "Animate a reference image with Veo 3.1.",
    unit: "per_second",
    unitPriceUsd: 0.4,
    capabilities: { imageToVideo: true, hasAudio: true, maxResolution: "1080p" },
    features: ["image-to-video", "native-audio"],
    sortIndex: 3,
  },
  {
    slug: "fal-ai/veo2",
    category: "video",
    displayName: "Veo 2",
    description: "Previous-gen Veo, billed per 5-second clip.",
    unit: "per_5_second_video",
    unitPriceUsd: 1.25,
    capabilities: { textToVideo: true, hasAudio: false, maxResolution: "720p" },
    features: ["text-to-video"],
    sortIndex: 9,
  },
  {
    slug: "fal-ai/veo2/image-to-video",
    category: "video",
    displayName: "Veo 2 (Image-to-Video)",
    unit: "per_5_second_video",
    unitPriceUsd: 1.25,
    capabilities: { imageToVideo: true, maxResolution: "720p" },
    features: ["image-to-video"],
    sortIndex: 10,
  },

  // Kling v3
  {
    slug: "fal-ai/kling-video/v3/pro/text-to-video",
    category: "video",
    displayName: "Kling v3 Pro",
    description: "Multi-shot subject consistency with native audio.",
    unit: "per_second",
    unitPriceUsd: 0.1,
    capabilities: { textToVideo: true, hasAudio: true, maxResolution: "1080p" },
    features: ["text-to-video", "native-audio", "multi-shot"],
    badge: "hot",
    marketingBlurb: "Best price/quality for cinematic clips with natural motion.",
    sortIndex: 4,
  },
  {
    slug: "fal-ai/kling-video/v3/pro/image-to-video",
    category: "video",
    displayName: "Kling v3 Pro (Image-to-Video)",
    unit: "per_second",
    unitPriceUsd: 0.1,
    capabilities: { imageToVideo: true, hasAudio: true, maxResolution: "1080p" },
    features: ["image-to-video", "native-audio"],
    sortIndex: 5,
  },
  {
    slug: "fal-ai/kling-video/v3/4k/text-to-video",
    category: "video",
    displayName: "Kling v3 4K",
    description: "Native 4K output without an upscale pass.",
    unit: "per_second",
    unitPriceUsd: 0.18,
    capabilities: { textToVideo: true, hasAudio: false, maxResolution: "4K" },
    features: ["text-to-video", "4K"],
    badge: "premium",
    sortIndex: 6,
  },
  {
    slug: "fal-ai/kling-video/v3/4k/image-to-video",
    category: "video",
    displayName: "Kling v3 4K (Image-to-Video)",
    unit: "per_second",
    unitPriceUsd: 0.18,
    capabilities: { imageToVideo: true, maxResolution: "4K" },
    features: ["image-to-video", "4K"],
    sortIndex: 7,
  },
  {
    slug: "fal-ai/kling-video/o3/4k/text-to-video",
    category: "video",
    displayName: "Kling O3 4K",
    description: "Stylised native 4K with transform features.",
    unit: "per_second",
    unitPriceUsd: 0.18,
    capabilities: { textToVideo: true, maxResolution: "4K" },
    features: ["text-to-video", "4K", "stylised"],
    sortIndex: 8,
  },
  {
    slug: "fal-ai/kling-video/o3/4k/image-to-video",
    category: "video",
    displayName: "Kling O3 4K (Image-to-Video)",
    unit: "per_second",
    unitPriceUsd: 0.18,
    capabilities: { imageToVideo: true, maxResolution: "4K" },
    features: ["image-to-video", "4K"],
    sortIndex: 11,
  },

  // Kling v2.5 Turbo
  {
    slug: "fal-ai/kling-video/v2.5-turbo/pro/image-to-video",
    category: "video",
    displayName: "Kling 2.5 Turbo Pro",
    description: "Faster Kling, billed per second.",
    unit: "per_second",
    unitPriceUsd: 0.07,
    capabilities: { imageToVideo: true, hasAudio: false, maxResolution: "1080p" },
    features: ["image-to-video", "fast"],
    badge: "fast",
    sortIndex: 12,
  },

  // Kling v2 Master
  {
    slug: "fal-ai/kling-video/v2/master/text-to-video",
    category: "video",
    displayName: "Kling v2 Master",
    unit: "per_5_second_video",
    unitPriceUsd: 1.4,
    capabilities: { textToVideo: true, maxResolution: "1080p" },
    features: ["text-to-video"],
    sortIndex: 13,
  },
  {
    slug: "fal-ai/kling-video/v2/master/image-to-video",
    category: "video",
    displayName: "Kling v2 Master (I2V)",
    unit: "per_5_second_video",
    unitPriceUsd: 1.4,
    capabilities: { imageToVideo: true, maxResolution: "1080p" },
    features: ["image-to-video"],
    sortIndex: 14,
  },

  // Kling v1.6
  {
    slug: "fal-ai/kling-video/v1.6/pro/text-to-video",
    category: "video",
    displayName: "Kling 1.6 Pro",
    unit: "per_video_second",
    unitPriceUsd: 0.095,
    capabilities: { textToVideo: true, maxResolution: "1080p" },
    features: ["text-to-video"],
    sortIndex: 15,
  },
  {
    slug: "fal-ai/kling-video/v1.6/pro/image-to-video",
    category: "video",
    displayName: "Kling 1.6 Pro (I2V)",
    unit: "per_video_second",
    unitPriceUsd: 0.095,
    capabilities: { imageToVideo: true, maxResolution: "1080p" },
    features: ["image-to-video"],
    sortIndex: 16,
  },
  {
    slug: "fal-ai/kling-video/v1.6/standard/text-to-video",
    category: "video",
    displayName: "Kling 1.6 Standard",
    unit: "per_video_second",
    unitPriceUsd: 0.045,
    capabilities: { textToVideo: true, maxResolution: "720p" },
    features: ["text-to-video", "fast"],
    sortIndex: 17,
  },
  {
    slug: "fal-ai/kling-video/v1.6/standard/image-to-video",
    category: "video",
    displayName: "Kling 1.6 Standard (I2V)",
    unit: "per_video_second",
    unitPriceUsd: 0.045,
    capabilities: { imageToVideo: true, maxResolution: "720p" },
    features: ["image-to-video", "fast"],
    sortIndex: 18,
  },
  {
    slug: "fal-ai/kling-video/v1.5/pro/text-to-video",
    category: "video",
    displayName: "Kling 1.5 Pro",
    unit: "per_video_second",
    unitPriceUsd: 0.1,
    capabilities: { textToVideo: true, maxResolution: "1080p" },
    features: ["text-to-video"],
    sortIndex: 19,
  },
  {
    slug: "fal-ai/kling-video/v1.5/pro/image-to-video",
    category: "video",
    displayName: "Kling 1.5 Pro (I2V)",
    unit: "per_video_second",
    unitPriceUsd: 0.1,
    capabilities: { imageToVideo: true, maxResolution: "1080p" },
    features: ["image-to-video"],
    sortIndex: 20,
  },

  // Seedance
  {
    slug: "fal-ai/bytedance/seedance-2.0/text-to-video",
    category: "video",
    displayName: "Seedance 2 Text-to-Video",
    description: "ByteDance's flagship — multi-shot, native audio, real-world physics.",
    unit: "per_second",
    unitPriceUsd: 0.08,
    capabilities: { textToVideo: true, hasAudio: true, maxResolution: "1080p" },
    features: ["text-to-video", "native-audio", "multi-shot"],
    badge: "new",
    sortIndex: 21,
  },
  {
    slug: "fal-ai/bytedance/seedance-2.0/image-to-video",
    category: "video",
    displayName: "Seedance 2 Image-to-Video",
    unit: "per_second",
    unitPriceUsd: 0.08,
    capabilities: { imageToVideo: true, hasAudio: true, maxResolution: "1080p" },
    features: ["image-to-video", "native-audio"],
    badge: "new",
    sortIndex: 22,
  },
  {
    slug: "fal-ai/bytedance/seedance-2.0/fast/text-to-video",
    category: "video",
    displayName: "Seedance 2 Fast",
    unit: "per_second",
    unitPriceUsd: 0.05,
    capabilities: { textToVideo: true, hasAudio: true },
    features: ["text-to-video", "fast"],
    badge: "fast",
    sortIndex: 23,
  },
  {
    slug: "fal-ai/bytedance/seedance-2.0/fast/image-to-video",
    category: "video",
    displayName: "Seedance 2 Fast (I2V)",
    unit: "per_second",
    unitPriceUsd: 0.05,
    capabilities: { imageToVideo: true, hasAudio: true },
    features: ["image-to-video", "fast"],
    sortIndex: 24,
  },

  // Wan
  {
    slug: "fal-ai/wan-25-preview/text-to-video",
    category: "video",
    displayName: "Wan 2.5 Preview",
    description: "Cheapest tier — great for drafts and storyboards.",
    unit: "per_second",
    unitPriceUsd: 0.05,
    capabilities: { textToVideo: true },
    features: ["text-to-video", "draft"],
    sortIndex: 25,
  },
  {
    slug: "fal-ai/wan-pro/text-to-video",
    category: "video",
    displayName: "Wan Pro",
    unit: "per_5_second_video",
    unitPriceUsd: 0.8,
    capabilities: { textToVideo: true, maxResolution: "1080p" },
    features: ["text-to-video"],
    sortIndex: 26,
  },
  {
    slug: "fal-ai/wan-pro/image-to-video",
    category: "video",
    displayName: "Wan Pro (I2V)",
    unit: "per_5_second_video",
    unitPriceUsd: 0.8,
    capabilities: { imageToVideo: true, maxResolution: "1080p" },
    features: ["image-to-video"],
    sortIndex: 27,
  },
  {
    slug: "fal-ai/wan-i2v",
    category: "video",
    displayName: "Wan I2V (480p)",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { imageToVideo: true, maxResolution: "480p" },
    features: ["image-to-video"],
    sortIndex: 28,
  },
  {
    slug: "fal-ai/wan-flf2v",
    category: "video",
    displayName: "Wan First-Last-Frame to Video",
    description: "Animate between two stills with smooth interpolation.",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { firstLastFrame: true, maxResolution: "480p" },
    features: ["first-last-frame"],
    sortIndex: 29,
  },
  {
    slug: "fal-ai/wan-effects",
    category: "effects",
    displayName: "Wan Effects",
    unit: "per_video",
    unitPriceUsd: 0.35,
    capabilities: { effects: true },
    features: ["effects"],
    sortIndex: 30,
  },
  {
    slug: "fal-ai/wan-vace",
    category: "video",
    displayName: "Wan VACE",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: {},
    features: ["video"],
    sortIndex: 31,
  },
  {
    slug: "fal-ai/wan-t2v-lora",
    category: "video",
    displayName: "Wan T2V LoRA",
    unit: "per_video",
    unitPriceUsd: 0.75,
    capabilities: { supportsLora: true, textToVideo: true },
    features: ["text-to-video", "lora"],
    sortIndex: 32,
  },
  {
    slug: "fal-ai/wan/v2.1/1.3b/text-to-video",
    category: "video",
    displayName: "Wan 2.1 1.3B",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 33,
  },

  // Pika
  {
    slug: "fal-ai/pika/v2.2/text-to-video",
    category: "video",
    displayName: "Pika 2.2",
    unit: "per_5_second_video",
    unitPriceUsd: 0.45,
    capabilities: { textToVideo: true, maxResolution: "1080p" },
    features: ["text-to-video"],
    sortIndex: 34,
  },
  {
    slug: "fal-ai/pika/v2.2/image-to-video",
    category: "video",
    displayName: "Pika 2.2 (I2V)",
    unit: "per_5_second_video",
    unitPriceUsd: 0.45,
    capabilities: { imageToVideo: true, maxResolution: "1080p" },
    features: ["image-to-video"],
    sortIndex: 35,
  },
  {
    slug: "fal-ai/pika/v2.2/pikascenes",
    category: "video",
    displayName: "Pika 2.2 Pikascenes",
    unit: "per_5_second_video",
    unitPriceUsd: 0.45,
    capabilities: { multiScene: true, maxResolution: "1080p" },
    features: ["pikascenes"],
    sortIndex: 36,
  },
  {
    slug: "fal-ai/pika/v2/turbo/text-to-video",
    category: "video",
    displayName: "Pika 2 Turbo",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { textToVideo: true },
    features: ["text-to-video", "fast"],
    sortIndex: 37,
  },
  {
    slug: "fal-ai/pika/v2/turbo/image-to-video",
    category: "video",
    displayName: "Pika 2 Turbo (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 38,
  },
  {
    slug: "fal-ai/pika/v2.1/text-to-video",
    category: "video",
    displayName: "Pika 2.1",
    unit: "per_video",
    unitPriceUsd: 0.4,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 39,
  },
  {
    slug: "fal-ai/pika/v2.1/image-to-video",
    category: "video",
    displayName: "Pika 2.1 (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.4,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 40,
  },
  {
    slug: "fal-ai/pika/v1.5/pikaffects",
    category: "effects",
    displayName: "Pika Pikaffects",
    description: "Pika's effects pack: explode, melt, and others.",
    unit: "per_video",
    unitPriceUsd: 0.465,
    capabilities: { effects: true },
    features: ["effects"],
    sortIndex: 41,
  },

  // Pixverse
  {
    slug: "fal-ai/pixverse/v6/image-to-video",
    category: "video",
    displayName: "PixVerse v6",
    description: "Lifelike physics with strong motion.",
    unit: "per_5_second_video",
    unitPriceUsd: 0.45,
    capabilities: { imageToVideo: true, maxResolution: "720p" },
    features: ["image-to-video"],
    sortIndex: 42,
  },
  {
    slug: "fal-ai/pixverse/v3.5/text-to-video",
    category: "video",
    displayName: "PixVerse 3.5",
    unit: "per_5_second_video",
    unitPriceUsd: 0.4,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 43,
  },
  {
    slug: "fal-ai/pixverse/v3.5/image-to-video",
    category: "video",
    displayName: "PixVerse 3.5 (I2V)",
    unit: "per_5_second_video",
    unitPriceUsd: 0.4,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 44,
  },
  {
    slug: "fal-ai/pixverse/v3.5/effects",
    category: "effects",
    displayName: "PixVerse Effects",
    unit: "per_5_second_video",
    unitPriceUsd: 0.6,
    capabilities: { effects: true },
    features: ["effects"],
    sortIndex: 45,
  },
  {
    slug: "fal-ai/pixverse/v3.5/transition",
    category: "video",
    displayName: "PixVerse Transition",
    unit: "per_5_second_video",
    unitPriceUsd: 0.6,
    capabilities: { transition: true },
    features: ["transition"],
    sortIndex: 46,
  },

  // Luma Ray
  {
    slug: "fal-ai/luma-dream-machine/ray-2",
    category: "video",
    displayName: "Luma Ray 2",
    description: "Smooth motion and detail from Luma.",
    unit: "per_video",
    unitPriceUsd: 0.5,
    capabilities: { textToVideo: true, maxResolution: "720p" },
    features: ["text-to-video"],
    sortIndex: 47,
  },
  {
    slug: "fal-ai/luma-dream-machine/ray-2/image-to-video",
    category: "video",
    displayName: "Luma Ray 2 (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.5,
    capabilities: { imageToVideo: true, maxResolution: "720p" },
    features: ["image-to-video"],
    sortIndex: 48,
  },
  {
    slug: "fal-ai/luma-dream-machine/ray-2-flash",
    category: "video",
    displayName: "Luma Ray 2 Flash",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { textToVideo: true },
    features: ["text-to-video", "fast"],
    sortIndex: 49,
  },
  {
    slug: "fal-ai/luma-dream-machine/ray-2-flash/image-to-video",
    category: "video",
    displayName: "Luma Ray 2 Flash (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { imageToVideo: true },
    features: ["image-to-video", "fast"],
    sortIndex: 50,
  },

  // Hunyuan video
  {
    slug: "fal-ai/hunyuan-video",
    category: "video",
    displayName: "Hunyuan Video",
    unit: "per_video",
    unitPriceUsd: 0.4,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 51,
  },
  {
    slug: "fal-ai/hunyuan-video-image-to-video",
    category: "video",
    displayName: "Hunyuan Video (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.4,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 52,
  },
  {
    slug: "fal-ai/hunyuan-video-img2vid-lora",
    category: "video",
    displayName: "Hunyuan Video LoRA (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.3,
    capabilities: { imageToVideo: true, supportsLora: true },
    features: ["image-to-video", "lora"],
    sortIndex: 53,
  },
  {
    slug: "fal-ai/hunyuan-video-lora",
    category: "video",
    displayName: "Hunyuan Video LoRA (T2V)",
    unit: "per_unit",
    unitPriceUsd: 0.4,
    capabilities: { textToVideo: true, supportsLora: true },
    features: ["text-to-video", "lora"],
    sortIndex: 54,
  },

  // Minimax
  {
    slug: "fal-ai/minimax/video-01-director",
    category: "video",
    displayName: "Minimax Video-01 Director",
    unit: "per_video",
    unitPriceUsd: 0.5,
    capabilities: { textToVideo: true },
    features: ["text-to-video", "director"],
    sortIndex: 55,
  },
  {
    slug: "fal-ai/minimax/video-01-director/image-to-video",
    category: "video",
    displayName: "Minimax Director (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.5,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 56,
  },
  {
    slug: "fal-ai/minimax/video-01-subject-reference",
    category: "video",
    displayName: "Minimax Subject Reference",
    unit: "per_video",
    unitPriceUsd: 0.5,
    capabilities: { subjectReference: true },
    features: ["subject-reference"],
    sortIndex: 57,
  },
  {
    slug: "fal-ai/minimax/video-01/image-to-video",
    category: "video",
    displayName: "Minimax Video-01 (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.5,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 58,
  },

  // Vidu
  {
    slug: "fal-ai/vidu/q1/text-to-video",
    category: "video",
    displayName: "Vidu Q1",
    unit: "per_5_second_video",
    unitPriceUsd: 0.6,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 59,
  },
  {
    slug: "fal-ai/vidu/q1/image-to-video",
    category: "video",
    displayName: "Vidu Q1 (I2V)",
    unit: "per_5_second_video",
    unitPriceUsd: 0.5,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 60,
  },
  {
    slug: "fal-ai/vidu/q1/start-end-to-video",
    category: "video",
    displayName: "Vidu Q1 Start-End",
    unit: "per_4_second_video",
    unitPriceUsd: 0.5,
    capabilities: { firstLastFrame: true },
    features: ["first-last-frame"],
    sortIndex: 61,
  },
  {
    slug: "fal-ai/vidu/reference-to-video",
    category: "video",
    displayName: "Vidu Reference-to-Video",
    unit: "per_4_second_video",
    unitPriceUsd: 0.4,
    capabilities: { reference: true },
    features: ["reference"],
    sortIndex: 62,
  },
  {
    slug: "fal-ai/vidu/template-to-video",
    category: "video",
    displayName: "Vidu Template",
    unit: "per_template",
    unitPriceUsd: 0.3,
    capabilities: { template: true },
    features: ["template"],
    sortIndex: 63,
  },
  {
    slug: "fal-ai/vidu/image-to-video",
    category: "video",
    displayName: "Vidu I2V",
    unit: "per_4_second_video",
    unitPriceUsd: 0.2,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 64,
  },

  // LTX-Video
  {
    slug: "fal-ai/ltx-video-v097",
    category: "video",
    displayName: "LTX Video 0.9.7",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 65,
  },
  {
    slug: "fal-ai/ltx-2-19b/image-to-video",
    category: "video",
    displayName: "LTX-2 19B (I2V)",
    description: "Generate video with audio from images.",
    unit: "per_video",
    unitPriceUsd: 0.3,
    capabilities: { imageToVideo: true, hasAudio: true },
    features: ["image-to-video", "audio"],
    badge: "new",
    sortIndex: 66,
  },
  {
    slug: "fal-ai/ltx-video-v095/image-to-video",
    category: "video",
    displayName: "LTX Video 0.9.5 (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.04,
    capabilities: { imageToVideo: true },
    features: ["image-to-video", "fast"],
    badge: "fast",
    sortIndex: 67,
  },

  // Cog/Magi/Skyreels/etc.
  {
    slug: "fal-ai/cogvideox-5b",
    category: "video",
    displayName: "CogVideoX 5B",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 68,
  },
  {
    slug: "fal-ai/magi",
    category: "video",
    displayName: "Magi",
    unit: "per_4_second_video",
    unitPriceUsd: 0.8,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 69,
  },
  {
    slug: "fal-ai/magi-distilled",
    category: "video",
    displayName: "Magi Distilled",
    unit: "per_4_second_video",
    unitPriceUsd: 0.32,
    capabilities: { textToVideo: true },
    features: ["text-to-video"],
    sortIndex: 70,
  },
  {
    slug: "fal-ai/magi-distilled/image-to-video",
    category: "video",
    displayName: "Magi Distilled (I2V)",
    unit: "per_4_second_video",
    unitPriceUsd: 0.32,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 71,
  },
  {
    slug: "fal-ai/skyreels-i2v",
    category: "video",
    displayName: "Skyreels I2V",
    unit: "per_video",
    unitPriceUsd: 0.3,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 72,
  },
  {
    slug: "fal-ai/stable-video",
    category: "video",
    displayName: "Stable Video",
    unit: "per_video",
    unitPriceUsd: 0.075,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 73,
  },
  {
    slug: "fal-ai/transpixar",
    category: "video",
    displayName: "TransPixar",
    unit: "per_video",
    unitPriceUsd: 0.4,
    capabilities: { textToVideo: true, transparency: true },
    features: ["text-to-video", "transparent-bg"],
    sortIndex: 74,
  },
  {
    slug: "fal-ai/framepack",
    category: "video",
    displayName: "Framepack",
    unit: "per_second",
    unitPriceUsd: 0.0333,
    capabilities: { videoEdit: true },
    features: ["video-edit"],
    sortIndex: 75,
  },
  {
    slug: "fal-ai/framepack/flf2v",
    category: "video",
    displayName: "Framepack First-Last-Frame",
    unit: "per_second",
    unitPriceUsd: 0.0333,
    capabilities: { firstLastFrame: true },
    features: ["first-last-frame"],
    sortIndex: 76,
  },
  {
    slug: "fal-ai/alibaba/happy-horse/text-to-video",
    category: "video",
    displayName: "Happy Horse 1.0",
    description: "Generate 1080p video with synchronized native audio.",
    unit: "per_second",
    unitPriceUsd: 0.07,
    capabilities: { textToVideo: true, hasAudio: true, maxResolution: "1080p", durationOpts: [3, 6, 9, 12, 15] },
    features: ["text-to-video", "native-audio"],
    badge: "new",
    sortIndex: 77,
  },
  {
    slug: "fal-ai/ovi/image-to-video",
    category: "video",
    displayName: "Ovi (I2V)",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { imageToVideo: true },
    features: ["image-to-video"],
    sortIndex: 78,
  },
  {
    slug: "fal-ai/ben/v2/video",
    category: "video",
    displayName: "BEN v2 Video",
    unit: "per_megapixel",
    unitPriceUsd: 0.001,
    capabilities: { videoEdit: true },
    features: ["video-edit"],
    sortIndex: 79,
  },
];

// ---------------------------------------------------------------------------
// Image generation
// ---------------------------------------------------------------------------
const IMAGE: ModelSeed[] = [
  {
    slug: "fal-ai/flux-pro/v1.1-ultra",
    category: "image",
    displayName: "FLUX 1.1 Pro Ultra",
    description: "Top-tier photorealistic and concept generation.",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { textToImage: true, maxResolution: "2K" },
    features: ["text-to-image", "premium"],
    badge: "premium",
    marketingBlurb: "Sharp detail, strong prompt adherence — the workhorse for hero imagery.",
    sortIndex: 100,
  },
  {
    slug: "fal-ai/flux-pro/v1.1-ultra-finetuned",
    category: "image",
    displayName: "FLUX 1.1 Pro Ultra (Finetuned)",
    unit: "per_image",
    unitPriceUsd: 0.07,
    capabilities: { textToImage: true, supportsLora: true },
    features: ["text-to-image", "lora"],
    sortIndex: 101,
  },
  {
    slug: "fal-ai/flux-pro/v1.1",
    category: "image",
    displayName: "FLUX 1.1 Pro",
    unit: "per_megapixel",
    unitPriceUsd: 0.04,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 102,
  },
  {
    slug: "fal-ai/flux-pro/kontext",
    category: "image",
    displayName: "FLUX Kontext Pro",
    description: "Style-locked image edits with text prompts.",
    unit: "per_image",
    unitPriceUsd: 0.04,
    capabilities: { imageEdit: true },
    features: ["edit"],
    sortIndex: 103,
  },
  {
    slug: "fal-ai/flux/dev",
    category: "image",
    displayName: "FLUX Dev",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { textToImage: true, supportsLora: true },
    features: ["text-to-image", "lora"],
    sortIndex: 104,
  },
  {
    slug: "fal-ai/flux-lora",
    category: "image",
    displayName: "FLUX LoRA",
    unit: "per_megapixel",
    unitPriceUsd: 0.035,
    capabilities: { textToImage: true, supportsLora: true },
    features: ["text-to-image", "lora"],
    sortIndex: 105,
  },
  {
    slug: "fal-ai/flux-lora-canny",
    category: "image",
    displayName: "FLUX LoRA Canny",
    unit: "per_megapixel",
    unitPriceUsd: 0.035,
    capabilities: { controlNet: "canny" },
    features: ["controlnet"],
    sortIndex: 106,
  },
  {
    slug: "fal-ai/flux-pro/v1/canny",
    category: "image",
    displayName: "FLUX Pro Canny",
    unit: "per_megapixel",
    unitPriceUsd: 0.05,
    capabilities: { controlNet: "canny" },
    features: ["controlnet"],
    sortIndex: 107,
  },
  {
    slug: "fal-ai/flux-pro/v1/depth",
    category: "image",
    displayName: "FLUX Pro Depth",
    unit: "per_megapixel",
    unitPriceUsd: 0.05,
    capabilities: { controlNet: "depth" },
    features: ["controlnet"],
    sortIndex: 108,
  },
  {
    slug: "fal-ai/flux-control-lora-canny",
    category: "image",
    displayName: "FLUX Control LoRA Canny",
    unit: "per_megapixel",
    unitPriceUsd: 0.04,
    capabilities: { controlNet: "canny", supportsLora: true },
    features: ["controlnet", "lora"],
    sortIndex: 109,
  },
  {
    slug: "fal-ai/flux-control-lora-depth",
    category: "image",
    displayName: "FLUX Control LoRA Depth",
    unit: "per_megapixel",
    unitPriceUsd: 0.04,
    capabilities: { controlNet: "depth", supportsLora: true },
    features: ["controlnet", "lora"],
    sortIndex: 110,
  },
  {
    slug: "fal-ai/flux-general",
    category: "image",
    displayName: "FLUX General",
    unit: "per_megapixel",
    unitPriceUsd: 0.075,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 111,
  },
  {
    slug: "fal-ai/nano-banana",
    category: "image",
    displayName: "Nano Banana",
    description: "Cheap and fast — perfect for previews.",
    unit: "per_image",
    unitPriceUsd: 0.0398,
    capabilities: { textToImage: true },
    features: ["text-to-image", "fast"],
    badge: "fast",
    sortIndex: 112,
  },
  {
    slug: "fal-ai/bytedance/seedream/v4/text-to-image",
    category: "image",
    displayName: "Seedream V4",
    unit: "per_image",
    unitPriceUsd: 0.03,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 113,
  },
  {
    slug: "fal-ai/ideogram/v3",
    category: "image",
    displayName: "Ideogram V3",
    description: "Best-in-class text rendering inside images.",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { textToImage: true, textInImage: true },
    features: ["text-to-image", "text-aware"],
    sortIndex: 114,
  },
  {
    slug: "fal-ai/ideogram/v3/edit",
    category: "image",
    displayName: "Ideogram V3 Edit",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { imageEdit: true, textInImage: true },
    features: ["edit"],
    sortIndex: 115,
  },
  {
    slug: "fal-ai/ideogram/v3/reframe",
    category: "image",
    displayName: "Ideogram V3 Reframe",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { reframe: true },
    features: ["reframe"],
    sortIndex: 116,
  },
  {
    slug: "fal-ai/ideogram/v3/remix",
    category: "image",
    displayName: "Ideogram V3 Remix",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { remix: true },
    features: ["remix"],
    sortIndex: 117,
  },
  {
    slug: "fal-ai/ideogram/v3/replace-background",
    category: "image",
    displayName: "Ideogram Replace Background",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { backgroundReplace: true },
    features: ["background"],
    sortIndex: 118,
  },
  {
    slug: "fal-ai/ideogram/v2a",
    category: "image",
    displayName: "Ideogram V2a",
    unit: "per_image",
    unitPriceUsd: 0.04,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 119,
  },
  {
    slug: "fal-ai/ideogram/v2a/turbo",
    category: "image",
    displayName: "Ideogram V2a Turbo",
    unit: "per_image",
    unitPriceUsd: 0.025,
    capabilities: { textToImage: true },
    features: ["text-to-image", "fast"],
    sortIndex: 120,
  },
  {
    slug: "fal-ai/imagen3",
    category: "image",
    displayName: "Imagen 3",
    unit: "per_image",
    unitPriceUsd: 0.05,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 121,
  },
  {
    slug: "fal-ai/imagen3/fast",
    category: "image",
    displayName: "Imagen 3 Fast",
    unit: "per_image",
    unitPriceUsd: 0.025,
    capabilities: { textToImage: true },
    features: ["text-to-image", "fast"],
    sortIndex: 122,
  },
  {
    slug: "fal-ai/hidream-i1-full",
    category: "image",
    displayName: "HiDream I1 Full",
    unit: "per_megapixel",
    unitPriceUsd: 0.05,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 123,
  },
  {
    slug: "fal-ai/hidream-i1-fast",
    category: "image",
    displayName: "HiDream I1 Fast",
    unit: "per_megapixel",
    unitPriceUsd: 0.01,
    capabilities: { textToImage: true },
    features: ["text-to-image", "fast"],
    sortIndex: 124,
  },
  {
    slug: "fal-ai/hidream-i1-dev",
    category: "image",
    displayName: "HiDream I1 Dev",
    unit: "per_megapixel",
    unitPriceUsd: 0.03,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 125,
  },
  {
    slug: "fal-ai/sana/sprint",
    category: "image",
    displayName: "SANA Sprint",
    description: "Ultra-low-latency image gen for realtime use.",
    unit: "per_megapixel",
    unitPriceUsd: 0.0025,
    capabilities: { textToImage: true, realtime: true },
    features: ["text-to-image", "realtime"],
    badge: "fast",
    sortIndex: 126,
  },
  {
    slug: "fal-ai/sana/v1.5/1.6b",
    category: "image",
    displayName: "SANA 1.5 1.6B",
    unit: "per_megapixel",
    unitPriceUsd: 0.0075,
    capabilities: { textToImage: true },
    features: ["text-to-image", "fast"],
    sortIndex: 127,
  },
  {
    slug: "fal-ai/sana/v1.5/4.8b",
    category: "image",
    displayName: "SANA 1.5 4.8B",
    unit: "per_megapixel",
    unitPriceUsd: 0.01,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 128,
  },
  {
    slug: "fal-ai/aura-flow",
    category: "image",
    displayName: "AuraFlow",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 129,
  },
  {
    slug: "fal-ai/lumina-image/v2",
    category: "image",
    displayName: "Lumina Image v2",
    unit: "per_megapixel",
    unitPriceUsd: 0.075,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 130,
  },
  {
    slug: "fal-ai/minimax/image-01",
    category: "image",
    displayName: "Minimax Image-01",
    unit: "per_image",
    unitPriceUsd: 0.01,
    capabilities: { textToImage: true },
    features: ["text-to-image", "fast"],
    sortIndex: 131,
  },
  {
    slug: "fal-ai/minimax/image-01/subject-reference",
    category: "image",
    displayName: "Minimax Image-01 Subject Reference",
    unit: "per_image",
    unitPriceUsd: 0.01,
    capabilities: { subjectReference: true },
    features: ["subject-reference"],
    sortIndex: 132,
  },
  {
    slug: "fal-ai/stable-diffusion-v3-medium",
    category: "image",
    displayName: "SD3 Medium",
    unit: "per_image",
    unitPriceUsd: 0.035,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 133,
  },
  {
    slug: "fal-ai/stable-cascade",
    category: "image",
    displayName: "Stable Cascade",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 134,
  },
  {
    slug: "fal-ai/fast-lightning-sdxl",
    category: "image",
    displayName: "Fast Lightning SDXL",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { textToImage: true, realtime: true },
    features: ["text-to-image", "realtime"],
    sortIndex: 135,
  },
  {
    slug: "fal-ai/sdxl-controlnet-union",
    category: "image",
    displayName: "SDXL ControlNet Union",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { controlNet: "union" },
    features: ["controlnet"],
    sortIndex: 136,
  },
  {
    slug: "fal-ai/photomaker",
    category: "image",
    displayName: "PhotoMaker",
    unit: "per_compute_second",
    unitPriceUsd: 0.000575,
    capabilities: { face: true },
    features: ["face"],
    sortIndex: 137,
  },
  {
    slug: "fal-ai/instant-character",
    category: "image",
    displayName: "Instant Character",
    unit: "per_megapixel",
    unitPriceUsd: 0.1,
    capabilities: { face: true, character: true },
    features: ["character"],
    sortIndex: 138,
  },
  {
    slug: "fal-ai/cartoonify",
    category: "image",
    displayName: "Cartoonify",
    unit: "per_image",
    unitPriceUsd: 0.1,
    capabilities: { stylise: true },
    features: ["style"],
    sortIndex: 139,
  },
  {
    slug: "fal-ai/ghiblify",
    category: "image",
    displayName: "Ghiblify",
    description: "Ghibli-style illustrations from any reference.",
    unit: "per_image",
    unitPriceUsd: 0.05,
    capabilities: { stylise: true },
    features: ["style"],
    sortIndex: 140,
  },
  {
    slug: "fal-ai/gemini-flash-edit",
    category: "image",
    displayName: "Gemini Flash Edit",
    unit: "per_image",
    unitPriceUsd: 0.04,
    capabilities: { imageEdit: true },
    features: ["edit"],
    sortIndex: 141,
  },
  {
    slug: "fal-ai/gemini-flash-edit/multi",
    category: "image",
    displayName: "Gemini Flash Edit (Multi)",
    unit: "per_image",
    unitPriceUsd: 0.04,
    capabilities: { imageEdit: true, multi: true },
    features: ["edit"],
    sortIndex: 142,
  },
  {
    slug: "fal-ai/step1x-edit",
    category: "image",
    displayName: "Step1X Edit",
    unit: "per_megapixel",
    unitPriceUsd: 0.03,
    capabilities: { imageEdit: true },
    features: ["edit"],
    sortIndex: 143,
  },
  {
    slug: "fal-ai/qwen-image",
    category: "image",
    displayName: "Qwen Image",
    unit: "per_megapixel",
    unitPriceUsd: 0.02,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 144,
  },
  {
    slug: "fal-ai/omnigen-v1",
    category: "image",
    displayName: "OmniGen v1",
    unit: "per_megapixel",
    unitPriceUsd: 0.1,
    capabilities: { textToImage: true, multimodal: true },
    features: ["multimodal"],
    sortIndex: 145,
  },
  {
    slug: "fal-ai/uno",
    category: "image",
    displayName: "UNO",
    unit: "per_megapixel",
    unitPriceUsd: 0.05,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 146,
  },
  {
    slug: "fal-ai/f-lite/standard",
    category: "image",
    displayName: "F-Lite Standard",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { textToImage: true },
    features: ["text-to-image"],
    sortIndex: 147,
  },
  {
    slug: "fal-ai/f-lite/texture",
    category: "image",
    displayName: "F-Lite Texture",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { texture: true },
    features: ["texture"],
    sortIndex: 148,
  },
  {
    slug: "fal-ai/bria/background/remove",
    category: "image",
    displayName: "Bria Background Remove",
    unit: "per_generation",
    unitPriceUsd: 0.018,
    capabilities: { backgroundRemove: true },
    features: ["background"],
    sortIndex: 149,
  },
  {
    slug: "fal-ai/finegrain-eraser",
    category: "image",
    displayName: "Finegrain Eraser",
    unit: "per_request",
    unitPriceUsd: 0.27,
    capabilities: { erase: true },
    features: ["edit"],
    sortIndex: 150,
  },
  {
    slug: "fal-ai/codeformer",
    category: "image",
    displayName: "CodeFormer",
    description: "Face restoration and enhancement.",
    unit: "per_megapixel",
    unitPriceUsd: 0.0021,
    capabilities: { face: true, restore: true },
    features: ["face", "restore"],
    sortIndex: 151,
  },
  {
    slug: "fal-ai/nafnet/denoise",
    category: "image",
    displayName: "NAFNet Denoise",
    unit: "per_megapixel",
    unitPriceUsd: 0.0225,
    capabilities: { denoise: true },
    features: ["denoise"],
    sortIndex: 152,
  },
  {
    slug: "fal-ai/nafnet/deblur",
    category: "image",
    displayName: "NAFNet Deblur",
    unit: "per_megapixel",
    unitPriceUsd: 0.0225,
    capabilities: { deblur: true },
    features: ["deblur"],
    sortIndex: 153,
  },
  {
    slug: "fal-ai/mix-dehaze-net",
    category: "image",
    displayName: "Dehaze Net",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { dehaze: true },
    features: ["enhance"],
    sortIndex: 154,
  },
  {
    slug: "fal-ai/ddcolor",
    category: "image",
    displayName: "DDColor",
    description: "Colourise black & white images.",
    unit: "per_megapixel",
    unitPriceUsd: 0.001,
    capabilities: { colorise: true },
    features: ["colorise"],
    sortIndex: 155,
  },
  {
    slug: "fal-ai/ben/v2/image",
    category: "image",
    displayName: "BEN v2 Image",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { imageEdit: true },
    features: ["edit"],
    sortIndex: 156,
  },
  {
    slug: "fal-ai/star-vector",
    category: "image",
    displayName: "StarVector",
    unit: "per_megapixel",
    unitPriceUsd: 0.1,
    capabilities: { vector: true },
    features: ["vector"],
    sortIndex: 157,
  },
  {
    slug: "fal-ai/image2svg",
    category: "image",
    displayName: "Image to SVG",
    unit: "per_image",
    unitPriceUsd: 0.005,
    capabilities: { vector: true },
    features: ["vector"],
    sortIndex: 158,
  },
  {
    slug: "fal-ai/docres",
    category: "image",
    displayName: "DocRes",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { docEnhance: true },
    features: ["doc"],
    sortIndex: 159,
  },
  {
    slug: "fal-ai/docres/dewarp",
    category: "image",
    displayName: "DocRes Dewarp",
    unit: "per_megapixel",
    unitPriceUsd: 0.03,
    capabilities: { docEnhance: true },
    features: ["doc"],
    sortIndex: 160,
  },
  {
    slug: "fal-ai/hidream-e1-full",
    category: "image",
    displayName: "HiDream E1 Full",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { imageEdit: true },
    features: ["edit"],
    sortIndex: 161,
  },
  {
    slug: "fal-ai/evf-sam",
    category: "image",
    displayName: "EVF-SAM",
    unit: "per_request",
    unitPriceUsd: 0.005,
    capabilities: { segmentation: true },
    features: ["segment"],
    sortIndex: 162,
  },
  {
    slug: "fal-ai/sa2va/8b/image",
    category: "image",
    displayName: "Sa2VA 8B",
    unit: "per_mask",
    unitPriceUsd: 0.04,
    capabilities: { segmentation: true },
    features: ["segment"],
    sortIndex: 163,
  },
  {
    slug: "fal-ai/sam2/auto-segment",
    category: "image",
    displayName: "SAM 2 Auto Segment",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { segmentation: true },
    features: ["segment"],
    sortIndex: 164,
  },
  {
    slug: "fal-ai/flowedit",
    category: "image",
    displayName: "FlowEdit",
    unit: "per_compute_second",
    unitPriceUsd: 0.000575,
    capabilities: { imageEdit: true },
    features: ["edit"],
    sortIndex: 165,
  },
];

// ---------------------------------------------------------------------------
// Upscale
// ---------------------------------------------------------------------------
const UPSCALE: ModelSeed[] = [
  {
    slug: "fal-ai/topaz/upscale/video",
    category: "upscale",
    displayName: "Topaz Video Upscale",
    description: "Pro-grade video upscaler. Bills per output second.",
    unit: "per_second",
    unitPriceUsd: 0.1,
    capabilities: { videoUpscale: true, maxResolution: "4K" },
    features: ["video-upscale"],
    badge: "premium",
    sortIndex: 200,
  },
  {
    slug: "fal-ai/drct-super-resolution",
    category: "upscale",
    displayName: "DRCT Super Resolution",
    unit: "per_megapixel",
    unitPriceUsd: 0.0045,
    capabilities: { imageUpscale: true },
    features: ["image-upscale"],
    sortIndex: 201,
  },
  {
    slug: "fal-ai/creative-upscaler",
    category: "upscale",
    displayName: "Creative Upscaler",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { imageUpscale: true, creative: true },
    features: ["image-upscale", "creative"],
    sortIndex: 202,
  },
  {
    slug: "fal-ai/swin2sr",
    category: "upscale",
    displayName: "Swin2SR",
    unit: "per_megapixel",
    unitPriceUsd: 0.025,
    capabilities: { imageUpscale: true },
    features: ["image-upscale"],
    sortIndex: 203,
  },
  {
    slug: "fal-ai/esrgan",
    category: "upscale",
    displayName: "ESRGAN",
    unit: "per_compute_second",
    unitPriceUsd: 0.000575,
    capabilities: { imageUpscale: true },
    features: ["image-upscale"],
    sortIndex: 204,
  },
  {
    slug: "fal-ai/thera",
    category: "upscale",
    displayName: "Thera",
    unit: "per_megapixel",
    unitPriceUsd: 0.0021,
    capabilities: { imageUpscale: true },
    features: ["image-upscale"],
    sortIndex: 205,
  },
  {
    slug: "fal-ai/ideogram/upscale",
    category: "upscale",
    displayName: "Ideogram Upscale",
    unit: "per_image",
    unitPriceUsd: 0.06,
    capabilities: { imageUpscale: true },
    features: ["image-upscale"],
    sortIndex: 206,
  },
];

// ---------------------------------------------------------------------------
// Lipsync + avatar
// ---------------------------------------------------------------------------
const LIPSYNC_AVATAR: ModelSeed[] = [
  {
    slug: "fal-ai/sync-lipsync/v2",
    category: "lipsync",
    displayName: "Sync Lipsync 2.0",
    description: "Highest-fidelity audio-driven lipsync.",
    unit: "per_minute",
    unitPriceUsd: 3,
    capabilities: { audioToVideo: true, hasFace: true },
    features: ["lipsync", "premium"],
    badge: "premium",
    sortIndex: 300,
  },
  {
    slug: "fal-ai/sync-lipsync",
    category: "lipsync",
    displayName: "Sync Lipsync 1.x",
    unit: "per_minute",
    unitPriceUsd: 0.7,
    capabilities: { audioToVideo: true },
    features: ["lipsync"],
    sortIndex: 301,
  },
  {
    slug: "fal-ai/latentsync",
    category: "lipsync",
    displayName: "LatentSync",
    unit: "per_video",
    unitPriceUsd: 0.2,
    capabilities: { audioToVideo: true },
    features: ["lipsync"],
    sortIndex: 302,
  },
  {
    slug: "fal-ai/tavus/hummingbird-lipsync/v0",
    category: "lipsync",
    displayName: "Tavus Hummingbird",
    unit: "per_minute",
    unitPriceUsd: 2.1,
    capabilities: { audioToVideo: true },
    features: ["lipsync"],
    sortIndex: 303,
  },
  {
    slug: "fal-ai/kling-video/lipsync/audio-to-video",
    category: "lipsync",
    displayName: "Kling Lipsync (Audio→Video)",
    unit: "per_video",
    unitPriceUsd: 0.14,
    capabilities: { audioToVideo: true },
    features: ["lipsync"],
    sortIndex: 304,
  },
  {
    slug: "fal-ai/kling-video/lipsync/text-to-video",
    category: "lipsync",
    displayName: "Kling Lipsync (Text→Video)",
    unit: "per_video",
    unitPriceUsd: 0.14,
    capabilities: { textToLipsync: true },
    features: ["lipsync"],
    sortIndex: 305,
  },
  {
    slug: "fal-ai/fashn/tryon/v1.5",
    category: "avatar",
    displayName: "FASHN Try-On 1.5",
    description: "Garment swap on a model image.",
    unit: "per_generation",
    unitPriceUsd: 0.075,
    capabilities: { tryOn: true },
    features: ["try-on"],
    sortIndex: 306,
  },
  {
    slug: "fal-ai/cat-vton",
    category: "avatar",
    displayName: "CatVTON",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { tryOn: true },
    features: ["try-on"],
    sortIndex: 307,
  },
  {
    slug: "fal-ai/kling/v1-5/kolors-virtual-try-on",
    category: "avatar",
    displayName: "Kling Kolors Virtual Try-On",
    unit: "per_generation",
    unitPriceUsd: 0.07,
    capabilities: { tryOn: true },
    features: ["try-on"],
    sortIndex: 308,
  },
];

// ---------------------------------------------------------------------------
// Audio + TTS + STT
// ---------------------------------------------------------------------------
const AUDIO: ModelSeed[] = [
  {
    slug: "fal-ai/elevenlabs/tts/multilingual-v2",
    category: "tts",
    displayName: "ElevenLabs TTS Multilingual v2",
    description: "Industry-standard voiceover. 30+ languages.",
    unit: "per_1k_chars",
    unitPriceUsd: 0.1,
    capabilities: { multilingual: true },
    features: ["tts", "premium"],
    badge: "premium",
    sortIndex: 400,
  },
  {
    slug: "fal-ai/elevenlabs/tts/turbo-v2.5",
    category: "tts",
    displayName: "ElevenLabs TTS Turbo v2.5",
    unit: "per_1k_chars",
    unitPriceUsd: 0.05,
    capabilities: { multilingual: true, fast: true },
    features: ["tts", "fast"],
    sortIndex: 401,
  },
  {
    slug: "fal-ai/elevenlabs/sound-effects",
    category: "audio",
    displayName: "ElevenLabs Sound Effects",
    unit: "per_second",
    unitPriceUsd: 0.002,
    capabilities: { sfx: true },
    features: ["sfx"],
    sortIndex: 402,
  },
  {
    slug: "fal-ai/elevenlabs/audio-isolation",
    category: "audio",
    displayName: "ElevenLabs Audio Isolation",
    unit: "per_minute",
    unitPriceUsd: 0.1,
    capabilities: { audioCleanup: true },
    features: ["isolate"],
    sortIndex: 403,
  },
  {
    slug: "fal-ai/elevenlabs/speech-to-text",
    category: "stt",
    displayName: "ElevenLabs Speech-to-Text",
    unit: "per_minute",
    unitPriceUsd: 0.03,
    capabilities: { stt: true },
    features: ["stt"],
    sortIndex: 404,
  },
  {
    slug: "fal-ai/minimax/speech-02-hd",
    category: "tts",
    displayName: "Minimax Speech-02 HD",
    unit: "per_1k_chars",
    unitPriceUsd: 0.05,
    capabilities: { multilingual: true },
    features: ["tts"],
    sortIndex: 405,
  },
  {
    slug: "fal-ai/minimax/speech-02-turbo",
    category: "tts",
    displayName: "Minimax Speech-02 Turbo",
    unit: "per_1k_chars",
    unitPriceUsd: 0.03,
    capabilities: { multilingual: true, fast: true },
    features: ["tts", "fast"],
    sortIndex: 406,
  },
  {
    slug: "fal-ai/minimax/voice-clone",
    category: "tts",
    displayName: "Minimax Voice Clone",
    description: "Clone a voice from a sample. One-time fee per voice.",
    unit: "per_voice",
    unitPriceUsd: 1,
    capabilities: { voiceClone: true },
    features: ["voice-clone"],
    sortIndex: 407,
  },
  {
    slug: "fal-ai/orpheus-tts",
    category: "tts",
    displayName: "Orpheus TTS",
    unit: "per_1k_chars",
    unitPriceUsd: 0.05,
    capabilities: {},
    features: ["tts"],
    sortIndex: 408,
  },
  {
    slug: "fal-ai/dia-tts",
    category: "tts",
    displayName: "Dia TTS",
    unit: "per_1k_chars",
    unitPriceUsd: 0.04,
    capabilities: {},
    features: ["tts"],
    sortIndex: 409,
  },
  {
    slug: "fal-ai/dia-tts/voice-clone",
    category: "tts",
    displayName: "Dia TTS Voice Clone",
    unit: "per_1k_chars",
    unitPriceUsd: 0.04,
    capabilities: { voiceClone: true },
    features: ["voice-clone"],
    sortIndex: 410,
  },
  {
    slug: "fal-ai/zonos",
    category: "tts",
    displayName: "Zonos",
    unit: "per_1k_chars",
    unitPriceUsd: 0.05,
    capabilities: {},
    features: ["tts"],
    sortIndex: 411,
  },
  {
    slug: "fal-ai/csm-1b",
    category: "tts",
    displayName: "CSM 1B",
    unit: "per_1k_chars",
    unitPriceUsd: 0.03,
    capabilities: {},
    features: ["tts"],
    sortIndex: 412,
  },
  {
    slug: "fal-ai/kokoro/american-english",
    category: "tts",
    displayName: "Kokoro – American English",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "en-US" },
    features: ["tts"],
    sortIndex: 413,
  },
  {
    slug: "fal-ai/kokoro/british-english",
    category: "tts",
    displayName: "Kokoro – British English",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "en-GB" },
    features: ["tts"],
    sortIndex: 414,
  },
  {
    slug: "fal-ai/kokoro/spanish",
    category: "tts",
    displayName: "Kokoro – Spanish",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "es" },
    features: ["tts"],
    sortIndex: 415,
  },
  {
    slug: "fal-ai/kokoro/french",
    category: "tts",
    displayName: "Kokoro – French",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "fr" },
    features: ["tts"],
    sortIndex: 416,
  },
  {
    slug: "fal-ai/kokoro/italian",
    category: "tts",
    displayName: "Kokoro – Italian",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "it" },
    features: ["tts"],
    sortIndex: 417,
  },
  {
    slug: "fal-ai/kokoro/japanese",
    category: "tts",
    displayName: "Kokoro – Japanese",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "ja" },
    features: ["tts"],
    sortIndex: 418,
  },
  {
    slug: "fal-ai/kokoro/mandarin-chinese",
    category: "tts",
    displayName: "Kokoro – Mandarin",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "zh" },
    features: ["tts"],
    sortIndex: 419,
  },
  {
    slug: "fal-ai/kokoro/hindi",
    category: "tts",
    displayName: "Kokoro – Hindi",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "hi" },
    features: ["tts"],
    sortIndex: 420,
  },
  {
    slug: "fal-ai/kokoro/brazilian-portuguese",
    category: "tts",
    displayName: "Kokoro – Brazilian Portuguese",
    unit: "per_1k_chars",
    unitPriceUsd: 0.02,
    capabilities: { language: "pt-BR" },
    features: ["tts"],
    sortIndex: 421,
  },
  {
    slug: "fal-ai/whisper",
    category: "stt",
    displayName: "Whisper",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { stt: true },
    features: ["stt"],
    sortIndex: 422,
  },
  {
    slug: "fal-ai/speech-to-text",
    category: "stt",
    displayName: "Speech-to-Text",
    unit: "per_audio_second",
    unitPriceUsd: 0.0008,
    capabilities: { stt: true },
    features: ["stt"],
    sortIndex: 423,
  },
  {
    slug: "fal-ai/speech-to-text/turbo",
    category: "stt",
    displayName: "Speech-to-Text Turbo",
    unit: "per_audio_second",
    unitPriceUsd: 0.0008,
    capabilities: { stt: true, fast: true },
    features: ["stt", "fast"],
    sortIndex: 424,
  },
  {
    slug: "fal-ai/ace-step",
    category: "audio",
    displayName: "Ace-Step",
    description: "Music and audio generation.",
    unit: "per_second",
    unitPriceUsd: 0.005,
    capabilities: { music: true },
    features: ["music"],
    sortIndex: 425,
  },
  {
    slug: "fal-ai/ace-step/prompt-to-audio",
    category: "audio",
    displayName: "Ace-Step Prompt-to-Audio",
    unit: "per_second",
    unitPriceUsd: 0.005,
    capabilities: { music: true },
    features: ["music"],
    sortIndex: 426,
  },
  {
    slug: "fal-ai/mmaudio-v2",
    category: "audio",
    displayName: "MMAudio v2",
    description: "Generate matching audio for video clips.",
    unit: "per_second",
    unitPriceUsd: 0.001,
    capabilities: { videoToAudio: true },
    features: ["video-to-audio"],
    sortIndex: 427,
  },
  {
    slug: "fal-ai/yue",
    category: "audio",
    displayName: "Yue",
    unit: "per_second",
    unitPriceUsd: 0.05,
    capabilities: { music: true },
    features: ["music"],
    sortIndex: 428,
  },
  {
    slug: "fal-ai/diffrhythm",
    category: "audio",
    displayName: "DiffRhythm",
    unit: "per_10_seconds",
    unitPriceUsd: 0.01,
    capabilities: { music: true },
    features: ["music"],
    sortIndex: 429,
  },
];

// ---------------------------------------------------------------------------
// 3D
// ---------------------------------------------------------------------------
const THREE_D: ModelSeed[] = [
  {
    slug: "fal-ai/hunyuan3d/v2",
    category: "3d",
    displayName: "Hunyuan3D v2",
    description: "Generate 3D meshes from a single image.",
    unit: "per_generation",
    unitPriceUsd: 0.16,
    capabilities: { imageTo3D: true },
    features: ["3d"],
    badge: "premium",
    sortIndex: 500,
  },
  {
    slug: "fal-ai/hunyuan3d/v2/turbo",
    category: "3d",
    displayName: "Hunyuan3D v2 Turbo",
    unit: "per_generation",
    unitPriceUsd: 0.14,
    capabilities: { imageTo3D: true, fast: true },
    features: ["3d", "fast"],
    sortIndex: 501,
  },
  {
    slug: "fal-ai/hunyuan3d/v2/mini",
    category: "3d",
    displayName: "Hunyuan3D v2 Mini",
    unit: "per_generation",
    unitPriceUsd: 0.1,
    capabilities: { imageTo3D: true },
    features: ["3d"],
    sortIndex: 502,
  },
  {
    slug: "fal-ai/hunyuan3d/v2/mini/turbo",
    category: "3d",
    displayName: "Hunyuan3D v2 Mini Turbo",
    unit: "per_generation",
    unitPriceUsd: 0.08,
    capabilities: { imageTo3D: true, fast: true },
    features: ["3d", "fast"],
    sortIndex: 503,
  },
  {
    slug: "fal-ai/hunyuan3d/v2/multi-view",
    category: "3d",
    displayName: "Hunyuan3D v2 Multi-View",
    unit: "per_generation",
    unitPriceUsd: 0.017,
    capabilities: { imageTo3D: true, multiView: true },
    features: ["3d", "multi-view"],
    sortIndex: 504,
  },
  {
    slug: "fal-ai/hunyuan3d/v2/multi-view/turbo",
    category: "3d",
    displayName: "Hunyuan3D Multi-View Turbo",
    unit: "per_generation",
    unitPriceUsd: 0.015,
    capabilities: { imageTo3D: true, multiView: true, fast: true },
    features: ["3d", "fast", "multi-view"],
    sortIndex: 505,
  },
  {
    slug: "fal-ai/trellis",
    category: "3d",
    displayName: "TRELLIS",
    unit: "per_unit",
    unitPriceUsd: 0.02,
    capabilities: { imageTo3D: true },
    features: ["3d"],
    sortIndex: 506,
  },
  {
    slug: "fal-ai/trellis/multi",
    category: "3d",
    displayName: "TRELLIS Multi-Image",
    unit: "per_unit",
    unitPriceUsd: 0.02,
    capabilities: { imageTo3D: true, multiView: true },
    features: ["3d", "multi-view"],
    sortIndex: 507,
  },
];

// ---------------------------------------------------------------------------
// Vision (used internally by agent for grounding)
// ---------------------------------------------------------------------------
const VISION: ModelSeed[] = [
  {
    slug: "fal-ai/got-ocr/v2",
    category: "vision",
    displayName: "GOT-OCR v2",
    unit: "per_image",
    unitPriceUsd: 0.05,
    capabilities: { ocr: true },
    features: ["ocr"],
    sortIndex: 600,
  },
  {
    slug: "fal-ai/moondream2",
    category: "vision",
    displayName: "Moondream2",
    unit: "per_1k_chars",
    unitPriceUsd: 0.01,
    capabilities: { vision: true },
    features: ["vision"],
    sortIndex: 601,
  },
  {
    slug: "fal-ai/moondream2/object-detection",
    category: "vision",
    displayName: "Moondream2 Object Detection",
    unit: "per_image",
    unitPriceUsd: 0.02,
    capabilities: { detect: true },
    features: ["detect"],
    sortIndex: 602,
  },
  {
    slug: "fal-ai/llavav15-13b",
    category: "vision",
    displayName: "LLaVA 1.5 13B",
    unit: "per_compute_second",
    unitPriceUsd: 0.000575,
    capabilities: { vision: true },
    features: ["vision"],
    sortIndex: 603,
  },
  {
    slug: "fal-ai/mini-cpm",
    category: "vision",
    displayName: "MiniCPM",
    unit: "per_compute_second",
    unitPriceUsd: 0.00111,
    capabilities: { vision: true },
    features: ["vision"],
    sortIndex: 604,
  },
];

// ---------------------------------------------------------------------------
// Training
// ---------------------------------------------------------------------------
const TRAINING: ModelSeed[] = [
  {
    slug: "fal-ai/flux-lora-fast-training",
    category: "training",
    displayName: "FLUX LoRA Fast Training",
    description: "Fine-tune FLUX in 5 minutes with 5–20 reference images.",
    unit: "per_training_run",
    unitPriceUsd: 2,
    capabilities: { lora: true, fast: true },
    features: ["training", "lora"],
    badge: "fast",
    sortIndex: 700,
  },
  {
    slug: "fal-ai/flux-pro-trainer",
    category: "training",
    displayName: "FLUX Pro Trainer",
    unit: "per_training_run",
    unitPriceUsd: 4,
    capabilities: { lora: true },
    features: ["training", "lora"],
    sortIndex: 701,
  },
  {
    slug: "fal-ai/turbo-flux-trainer",
    category: "training",
    displayName: "Turbo FLUX Trainer",
    unit: "per_step",
    unitPriceUsd: 0.0024,
    capabilities: { lora: true, fast: true },
    features: ["training", "lora", "fast"],
    sortIndex: 702,
  },
  {
    slug: "fal-ai/hunyuan-video-lora-training",
    category: "training",
    displayName: "Hunyuan Video LoRA Training",
    unit: "per_training_run",
    unitPriceUsd: 5,
    capabilities: { videoLora: true },
    features: ["training", "video", "lora"],
    sortIndex: 703,
  },
  {
    slug: "fal-ai/wan-trainer",
    category: "training",
    displayName: "Wan Trainer",
    unit: "per_step",
    unitPriceUsd: 0.005,
    capabilities: { videoLora: true },
    features: ["training", "video"],
    sortIndex: 704,
  },
];

// ---------------------------------------------------------------------------
// Text helpers
// ---------------------------------------------------------------------------
const TEXT: ModelSeed[] = [
  {
    slug: "fal-ai/video-prompt-generator",
    category: "text",
    displayName: "Video Prompt Generator",
    description: "Optimise text prompts for video models.",
    unit: "per_request",
    unitPriceUsd: 0.011,
    capabilities: { promptOptimise: true },
    features: ["prompt"],
    sortIndex: 800,
  },
];

const ALL: ModelSeed[] = [...VIDEO, ...IMAGE, ...UPSCALE, ...LIPSYNC_AVATAR, ...AUDIO, ...THREE_D, ...VISION, ...TRAINING, ...TEXT];

async function main() {
  for (const m of ALL) {
    await prisma.falModel.upsert({
      where: { slug: m.slug },
      update: {
        category: m.category,
        displayName: m.displayName,
        description: m.description,
        unit: m.unit,
        unitPriceUsd: m.unitPriceUsd,
        capabilities: (m.capabilities ?? {}) as object,
        features: m.features ?? [],
        badge: m.badge,
        marketingBlurb: m.marketingBlurb,
        sortIndex: m.sortIndex ?? 0,
        enabled: true,
      },
      create: {
        slug: m.slug,
        category: m.category,
        displayName: m.displayName,
        description: m.description,
        unit: m.unit,
        unitPriceUsd: m.unitPriceUsd,
        capabilities: (m.capabilities ?? {}) as object,
        features: m.features ?? [],
        badge: m.badge,
        marketingBlurb: m.marketingBlurb,
        sortIndex: m.sortIndex ?? 0,
        enabled: true,
      },
    });
  }
  console.log(`seeded ${ALL.length} fal models`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
